/* eslint-disable */
import { FuseNavigationItem } from '@fuse/components/navigation';

export const defaultNavigation: FuseNavigationItem[] = [
    {
        "icon": "home",
        "menuId": 2,
        "id": "home",
        "title": "صفحه اصلی",
        "type": "basic",
        "parentId": 1,
        "translate": "home",
        "link": "/main/home",
        "children": [],
    },
    {
        "icon": "description",
        "menuId": 3,
        "id": "issueWalletGroup",
        "title": "اطلاعات پایه",
        "type": "collapsable",
        "parentId": 1,
        "translate": "اطلاعات پایه",
        "link": null,
        "children": [
            {
                "icon": "email",
                "menuId": 4,
                "id": "messages",
                "title": "پیام ها",
                "type": "basic",
                "parentId": 3,
                "translate": "پیام ها",
                "link": "/main/messages-management",
                "children": [],
            },
            {
                "icon": "featured_play_list",
                "menuId": 22,
                "id": "messages",
                "title": "قواعد",
                "type": "basic",
                "parentId": 3,
                "translate": "قواعد",
                "link": "/main/rules",
                "children": [],
            }
        ]
    },
    {
        "icon": "settings",
        "menuId": 30,
        "id": "issueWalletGroup",
        "title": "پیکربندی",
        "type": "collapsable",
        "parentId": 1,
        "translate": "پیکربندی",
        "link": null,
        "children": [
            {
                "icon": "device_hub",
                "menuId": 22,
                "id": "messages",
                "title": "هاب داده",
                "type": "basic",
                "parentId": 3,
                "translate": "هاب داده",
                "link": "/main/data-hub",
                "children": [],
            }
        ]
    },

    {
        "icon": "people",
        "menuId": 5,
        "id": "issueWalletGroup",
        "title": "سرویس گیرندگان",
        "type": "collapsable",
        "parentId": 1,
        "translate": "سرویس گیرندگان",
        "link": null,
        "children": [
            {
                "icon": "person",
                "menuId": 8,
                "id": "messages",
                "title": "سازمان",
                "type": "basic",
                "parentId": 5,
                "translate": "سازمان",
                "link": "/main/party",
                "children": [],
            }, {
                "icon": "device_hub",
                "menuId": 9,
                "id": "messages",
                "title": "ماژول",
                "type": "basic",
                "parentId": 5,
                "translate": "ماژول",
                "link": "/main/moduleBase",
                "children": [],
            }
        ],
    },
    {
        "icon": "account_balance",
        "menuId": 19,
        "id": "messages",
        "title": "کلاینت",
        "type": "basic",
        "parentId": 1,
        "translate": "کلاینت",
        "link": "/main/client",
        "children": [],
    },
    {
        "icon": "payments",
        "menuId": 27,
        "id": "payments",
        "title": "کارمزد سرویس",
        "type": "basic",
        "parentId": 1,
        "translate": "کارمزد سرویس",
        "link": "/main/wage-services",
        "children": [],
    },
    {
        "icon": "list_alt",
        "menuId": 10,
        "id": "messages",
        "title": "لیست دسترسی",
        "type": "basic",
        "parentId": 1,
        "translate": "لیست دسترسی",
        "link": "/main/access-list",
        "children": [],
    }, {
        "icon": "device_hub",
        "menuId": 11,
        "id": "messages",
        "title": "مدیاتور",
        "type": "collapsable",
        "parentId": 1,
        "translate": "مدیاتور",
        "children": [
            {
                "icon": "device_hub",
                "menuId": 22,
                "id": "messages",
                "title": "لیست مدیاتور ها",
                "type": "basic",
                "parentId": 11,
                "translate": "لیست مدیاتور ها",
                "link": "/main/mediators",
                "children": [],
            }, {
                "icon": "device_hub",
                "menuId": 20,
                "id": "messages",
                "title": "مدیاتور xml",
                "type": "basic",
                "parentId": 11,
                "translate": "مدیاتور xml",
                "link": "/main/mediatorsXml",
                "children": [],
            },
            {
                "icon": "device_hub",
                "menuId": 21,
                "id": "messages",
                "title": "مدیاتور json",
                "type": "basic",
                "parentId": 1,
                "translate": "مدیاتور json",
                "link": "/main/mediatorsJson",
                "children": [],
            }
        ],
    },
    /* {
         "icon": "supervised_user_circle",
         "menuId": 12,
         "id": "messages",
         "title": "مدیریت کاربران",
         "type": "collapsable",
         "parentId": 1,
         "translate": "مدیریت کاربران",
         "children": [
             {
                 "icon": "account_circle",
                 "menuId": 16,
                 "id": "messages",
                 "title": "کاربران",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "کاربران",
                 "link": "/main/users",
                 "children": [],
             },
             {
                 "icon": "account_circle",
                 "menuId": 17,
                 "id": "messages",
                 "title": "نقش ها",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "نقش ها",
                 "link": "/main/roles",
                 "children": [],
             },
         ],
     },
     {
         "icon": "supervised_user_circle",
         "menuId": 36,
         "id": "messages",
         "title": "مدیریت سیستم",
         "type": "collapsable",
         "parentId": 1,
         "translate": "مدیریت سیستم",
         "children": [
             {
                 "icon": "account_circle",
                 "menuId": 39,
                 "id": "messages",
                 "title": "کاربران",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "آلارمها",
                 "link": "/main/alerts",
                 "children": [],
             },

         ],
     }, */
    {
        "icon": "report",
        "menuId": 13,
        "id": "messages",
        "title": "گزارشات",
        "type": "collapsable",
        "parentId": 1,
        "translate": "گزارشات",
        "children": [
            {
                "icon": "report",
                "menuId": 25,
                "id": "messages",
                "title": "ریز کارکرد سرویس",
                "type": "basic",
                "parentId": 13,
                "translate": "ریز کارکرد سرویس",
                "link": "/main/log-reports",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 26,
                "id": "messages",
                "title": "فراخوانی تجمیعی سرویس‌ها",
                "type": "basic",
                "parentId": 13,
                "translate": "فراخوانی تجمیعی سرویس‌ها",
                "link": "/main/call-services-report",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 40,
                "id": "messages",
                "title": "نموداری",
                "type": "basic",
                "parentId": 13,
                "translate": "نموداری",
                "link": "/main/chart-report",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 44,
                "id": "messages",
                "title": "میزان پاسخ‌دهی",
                "type": "basic",
                "parentId": 13,
                "translate": "میزان پاسخ‌دهی",
                "link": "/main/response-rate",
                "children": [],
            },
        ],
    }, {
        "icon": "monetization_on",
        "menuId": 14,
        "id": "messages",
        "title": "صورت حساب",
        "type": "collapsable",
        "parentId": 1,
        "translate": "صورت حساب",
        "children": [
            {
                "icon": "monetization_on",
                "menuId": 18,
                "id": "messages",
                "title": "فاکتور",
                "type": "basic",
                "parentId": 14,
                "translate": "فاکتور",
                "link": "/main/factor",
                "children": [],
            },
            /* {
                 "icon": "monetization_on",
                 "menuId": 19,
                 "id": "messages",
                 "title": "هزینه ها",
                 "type": "basic",
                 "parentId": 14,
                 "translate": "هزینه ها",
                 "link": "/main/costs",
                 "children": [],
             },*/
        ],
    },
    {
        "icon": "web_asset",
        "menuId": 42,
        "id": "messages",
        "title": "api-store",
        "type": "collapsable",
        "parentId": 1,
        "translate": "api-store",
        "children": [
            {
                "icon": "assignment",
                "menuId": 43,
                "id": "messages",
                "title": "کارتابل صورتحساب",
                "type": "basic",
                "parentId": 1,
                "translate": "کارتابل صورتحساب",
                "link": "/main/bill-store",
                "children": [],
            },
        ]
    },
    {
        "icon": "feedback",
        "menuId": 15,
        "id": "messages",
        "title": "درباره...",
        "type": "basic",
        "parentId": 1,
        "translate": "درباره...",
        "link": "/main/about",
        "children": [],
    },
    {
        "icon": "exit_to_app",
        "menuId": 16,
        "id": "messages",
        "title": "خروج",
        "type": "basic",
        "parentId": 1,
        "translate": "خروج",
        "link": "/sign-out",
        "children": [],
    }
    ];
export const compactNavigation: FuseNavigationItem[] = [
    {
        "icon": "home",
        "menuId": 2,
        "id": "home",
        "title": "صفحه اصلی",
        "type": "basic",
        "parentId": 1,
        "translate": "home",
        "link": "/main/home",
        "children": [],
    },
    {
        "icon": "description",
        "menuId": 3,
        "id": "issueWalletGroup",
        "title": "اطلاعات پایه",
        "type": "collapsable",
        "parentId": 1,
        "translate": "اطلاعات پایه",
        "link": null,
        "children": [
            {
                "icon": "email",
                "menuId": 4,
                "id": "messages",
                "title": "پیام ها",
                "type": "basic",
                "parentId": 3,
                "translate": "پیام ها",
                "link": "/main/messages-management",
                "children": [],
            },
            {
                "icon": "featured_play_list",
                "menuId": 22,
                "id": "messages",
                "title": "قواعد",
                "type": "basic",
                "parentId": 3,
                "translate": "قواعد",
                "link": "/main/rules",
                "children": [],
            }
        ]
    },
    {
        "icon": "settings",
        "menuId": 30,
        "id": "issueWalletGroup",
        "title": "پیکربندی",
        "type": "collapsable",
        "parentId": 1,
        "translate": "پیکربندی",
        "link": null,
        "children": [
            {
                "icon": "device_hub",
                "menuId": 22,
                "id": "messages",
                "title": "هاب داده",
                "type": "basic",
                "parentId": 3,
                "translate": "هاب داده",
                "link": "/main/data-hub",
                "children": [],
            }
        ]
    },

    {
        "icon": "people",
        "menuId": 5,
        "id": "issueWalletGroup",
        "title": "سرویس گیرندگان",
        "type": "collapsable",
        "parentId": 1,
        "translate": "سرویس گیرندگان",
        "link": null,
        "children": [
            {
                "icon": "person",
                "menuId": 8,
                "id": "messages",
                "title": "سازمان",
                "type": "basic",
                "parentId": 5,
                "translate": "سازمان",
                "link": "/main/party",
                "children": [],
            }, {
                "icon": "device_hub",
                "menuId": 9,
                "id": "messages",
                "title": "ماژول",
                "type": "basic",
                "parentId": 5,
                "translate": "ماژول",
                "link": "/main/moduleBase",
                "children": [],
            }
        ],
    },
    {
        "icon": "account_balance",
        "menuId": 19,
        "id": "messages",
        "title": "کلاینت",
        "type": "basic",
        "parentId": 1,
        "translate": "کلاینت",
        "link": "/main/client",
        "children": [],
    },
    {
        "icon": "payments",
        "menuId": 27,
        "id": "payments",
        "title": "کارمزد سرویس",
        "type": "basic",
        "parentId": 1,
        "translate": "کارمزد سرویس",
        "link": "/main/wage-services",
        "children": [],
    },
    {
        "icon": "list_alt",
        "menuId": 10,
        "id": "messages",
        "title": "لیست دسترسی",
        "type": "basic",
        "parentId": 1,
        "translate": "لیست دسترسی",
        "link": "/main/access-list",
        "children": [],
    }, {
        "icon": "device_hub",
        "menuId": 11,
        "id": "messages",
        "title": "مدیاتور",
        "type": "collapsable",
        "parentId": 1,
        "translate": "مدیاتور",
        "children": [
            {
                "icon": "device_hub",
                "menuId": 22,
                "id": "messages",
                "title": "لیست مدیاتور ها",
                "type": "basic",
                "parentId": 11,
                "translate": "لیست مدیاتور ها",
                "link": "/main/mediators",
                "children": [],
            }, {
                "icon": "device_hub",
                "menuId": 20,
                "id": "messages",
                "title": "مدیاتور xml",
                "type": "basic",
                "parentId": 11,
                "translate": "مدیاتور xml",
                "link": "/main/mediatorsXml",
                "children": [],
            },
            {
                "icon": "device_hub",
                "menuId": 21,
                "id": "messages",
                "title": "مدیاتور json",
                "type": "basic",
                "parentId": 1,
                "translate": "مدیاتور json",
                "link": "/main/mediatorsJson",
                "children": [],
            }
        ],
    },
    /* {
         "icon": "supervised_user_circle",
         "menuId": 12,
         "id": "messages",
         "title": "مدیریت کاربران",
         "type": "collapsable",
         "parentId": 1,
         "translate": "مدیریت کاربران",
         "children": [
             {
                 "icon": "account_circle",
                 "menuId": 16,
                 "id": "messages",
                 "title": "کاربران",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "کاربران",
                 "link": "/main/users",
                 "children": [],
             },
             {
                 "icon": "account_circle",
                 "menuId": 17,
                 "id": "messages",
                 "title": "نقش ها",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "نقش ها",
                 "link": "/main/roles",
                 "children": [],
             },
         ],
     },
     {
         "icon": "supervised_user_circle",
         "menuId": 36,
         "id": "messages",
         "title": "مدیریت سیستم",
         "type": "collapsable",
         "parentId": 1,
         "translate": "مدیریت سیستم",
         "children": [
             {
                 "icon": "account_circle",
                 "menuId": 39,
                 "id": "messages",
                 "title": "کاربران",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "آلارمها",
                 "link": "/main/alerts",
                 "children": [],
             },

         ],
     }, */
    {
        "icon": "report",
        "menuId": 13,
        "id": "messages",
        "title": "گزارشات",
        "type": "collapsable",
        "parentId": 1,
        "translate": "گزارشات",
        "children": [
            {
                "icon": "report",
                "menuId": 25,
                "id": "messages",
                "title": "ریز کارکرد سرویس",
                "type": "basic",
                "parentId": 13,
                "translate": "ریز کارکرد سرویس",
                "link": "/main/log-reports",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 26,
                "id": "messages",
                "title": "فراخوانی تجمیعی سرویس‌ها",
                "type": "basic",
                "parentId": 13,
                "translate": "فراخوانی تجمیعی سرویس‌ها",
                "link": "/main/call-services-report",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 40,
                "id": "messages",
                "title": "نموداری",
                "type": "basic",
                "parentId": 13,
                "translate": "نموداری",
                "link": "/main/chart-report",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 44,
                "id": "messages",
                "title": "میزان پاسخ‌دهی",
                "type": "basic",
                "parentId": 13,
                "translate": "میزان پاسخ‌دهی",
                "link": "/main/response-rate",
                "children": [],
            },
        ],
    }, {
        "icon": "monetization_on",
        "menuId": 14,
        "id": "messages",
        "title": "صورت حساب",
        "type": "collapsable",
        "parentId": 1,
        "translate": "صورت حساب",
        "children": [
            {
                "icon": "monetization_on",
                "menuId": 18,
                "id": "messages",
                "title": "فاکتور",
                "type": "basic",
                "parentId": 14,
                "translate": "فاکتور",
                "link": "/main/factor",
                "children": [],
            },
            /* {
                 "icon": "monetization_on",
                 "menuId": 19,
                 "id": "messages",
                 "title": "هزینه ها",
                 "type": "basic",
                 "parentId": 14,
                 "translate": "هزینه ها",
                 "link": "/main/costs",
                 "children": [],
             },*/
        ],
    },
    {
        "icon": "web_asset",
        "menuId": 42,
        "id": "messages",
        "title": "api-store",
        "type": "collapsable",
        "parentId": 1,
        "translate": "api-store",
        "children": [
            {
                "icon": "assignment",
                "menuId": 43,
                "id": "messages",
                "title": "کارتابل صورتحساب",
                "type": "basic",
                "parentId": 1,
                "translate": "کارتابل صورتحساب",
                "link": "/main/bill-store",
                "children": [],
            },
        ]
    },
    {
        "icon": "feedback",
        "menuId": 15,
        "id": "messages",
        "title": "درباره...",
        "type": "basic",
        "parentId": 1,
        "translate": "درباره...",
        "link": "/main/about",
        "children": [],
    },
    {
        "icon": "exit_to_app",
        "menuId": 16,
        "id": "messages",
        "title": "خروج",
        "type": "basic",
        "parentId": 1,
        "translate": "خروج",
        "link": "/sign-out",
        "children": [],
    }
];
export const futuristicNavigation: FuseNavigationItem[] = [
    {
        "icon": "home",
        "menuId": 2,
        "id": "home",
        "title": "صفحه اصلی",
        "type": "basic",
        "parentId": 1,
        "translate": "home",
        "link": "/main/home",
        "children": [],
    },
    {
        "icon": "description",
        "menuId": 3,
        "id": "issueWalletGroup",
        "title": "اطلاعات پایه",
        "type": "collapsable",
        "parentId": 1,
        "translate": "اطلاعات پایه",
        "link": null,
        "children": [
            {
                "icon": "email",
                "menuId": 4,
                "id": "messages",
                "title": "پیام ها",
                "type": "basic",
                "parentId": 3,
                "translate": "پیام ها",
                "link": "/main/messages-management",
                "children": [],
            },
            {
                "icon": "featured_play_list",
                "menuId": 22,
                "id": "messages",
                "title": "قواعد",
                "type": "basic",
                "parentId": 3,
                "translate": "قواعد",
                "link": "/main/rules",
                "children": [],
            }
        ]
    },
    {
        "icon": "settings",
        "menuId": 30,
        "id": "issueWalletGroup",
        "title": "پیکربندی",
        "type": "collapsable",
        "parentId": 1,
        "translate": "پیکربندی",
        "link": null,
        "children": [
            {
                "icon": "device_hub",
                "menuId": 22,
                "id": "messages",
                "title": "هاب داده",
                "type": "basic",
                "parentId": 3,
                "translate": "هاب داده",
                "link": "/main/data-hub",
                "children": [],
            }
        ]
    },

    {
        "icon": "people",
        "menuId": 5,
        "id": "issueWalletGroup",
        "title": "سرویس گیرندگان",
        "type": "collapsable",
        "parentId": 1,
        "translate": "سرویس گیرندگان",
        "link": null,
        "children": [
            {
                "icon": "person",
                "menuId": 8,
                "id": "messages",
                "title": "سازمان",
                "type": "basic",
                "parentId": 5,
                "translate": "سازمان",
                "link": "/main/party",
                "children": [],
            }, {
                "icon": "device_hub",
                "menuId": 9,
                "id": "messages",
                "title": "ماژول",
                "type": "basic",
                "parentId": 5,
                "translate": "ماژول",
                "link": "/main/moduleBase",
                "children": [],
            }
        ],
    },
    {
        "icon": "account_balance",
        "menuId": 19,
        "id": "messages",
        "title": "کلاینت",
        "type": "basic",
        "parentId": 1,
        "translate": "کلاینت",
        "link": "/main/client",
        "children": [],
    },
    {
        "icon": "payments",
        "menuId": 27,
        "id": "payments",
        "title": "کارمزد سرویس",
        "type": "basic",
        "parentId": 1,
        "translate": "کارمزد سرویس",
        "link": "/main/wage-services",
        "children": [],
    },
    {
        "icon": "list_alt",
        "menuId": 10,
        "id": "messages",
        "title": "لیست دسترسی",
        "type": "basic",
        "parentId": 1,
        "translate": "لیست دسترسی",
        "link": "/main/access-list",
        "children": [],
    }, {
        "icon": "device_hub",
        "menuId": 11,
        "id": "messages",
        "title": "مدیاتور",
        "type": "collapsable",
        "parentId": 1,
        "translate": "مدیاتور",
        "children": [
            {
                "icon": "device_hub",
                "menuId": 22,
                "id": "messages",
                "title": "لیست مدیاتور ها",
                "type": "basic",
                "parentId": 11,
                "translate": "لیست مدیاتور ها",
                "link": "/main/mediators",
                "children": [],
            }, {
                "icon": "device_hub",
                "menuId": 20,
                "id": "messages",
                "title": "مدیاتور xml",
                "type": "basic",
                "parentId": 11,
                "translate": "مدیاتور xml",
                "link": "/main/mediatorsXml",
                "children": [],
            },
            {
                "icon": "device_hub",
                "menuId": 21,
                "id": "messages",
                "title": "مدیاتور json",
                "type": "basic",
                "parentId": 1,
                "translate": "مدیاتور json",
                "link": "/main/mediatorsJson",
                "children": [],
            }
        ],
    },
    /* {
         "icon": "supervised_user_circle",
         "menuId": 12,
         "id": "messages",
         "title": "مدیریت کاربران",
         "type": "collapsable",
         "parentId": 1,
         "translate": "مدیریت کاربران",
         "children": [
             {
                 "icon": "account_circle",
                 "menuId": 16,
                 "id": "messages",
                 "title": "کاربران",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "کاربران",
                 "link": "/main/users",
                 "children": [],
             },
             {
                 "icon": "account_circle",
                 "menuId": 17,
                 "id": "messages",
                 "title": "نقش ها",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "نقش ها",
                 "link": "/main/roles",
                 "children": [],
             },
         ],
     },
     {
         "icon": "supervised_user_circle",
         "menuId": 36,
         "id": "messages",
         "title": "مدیریت سیستم",
         "type": "collapsable",
         "parentId": 1,
         "translate": "مدیریت سیستم",
         "children": [
             {
                 "icon": "account_circle",
                 "menuId": 39,
                 "id": "messages",
                 "title": "کاربران",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "آلارمها",
                 "link": "/main/alerts",
                 "children": [],
             },

         ],
     }, */
    {
        "icon": "report",
        "menuId": 13,
        "id": "messages",
        "title": "گزارشات",
        "type": "collapsable",
        "parentId": 1,
        "translate": "گزارشات",
        "children": [
            {
                "icon": "report",
                "menuId": 25,
                "id": "messages",
                "title": "ریز کارکرد سرویس",
                "type": "basic",
                "parentId": 13,
                "translate": "ریز کارکرد سرویس",
                "link": "/main/log-reports",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 26,
                "id": "messages",
                "title": "فراخوانی تجمیعی سرویس‌ها",
                "type": "basic",
                "parentId": 13,
                "translate": "فراخوانی تجمیعی سرویس‌ها",
                "link": "/main/call-services-report",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 40,
                "id": "messages",
                "title": "نموداری",
                "type": "basic",
                "parentId": 13,
                "translate": "نموداری",
                "link": "/main/chart-report",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 44,
                "id": "messages",
                "title": "میزان پاسخ‌دهی",
                "type": "basic",
                "parentId": 13,
                "translate": "میزان پاسخ‌دهی",
                "link": "/main/response-rate",
                "children": [],
            },
        ],
    }, {
        "icon": "monetization_on",
        "menuId": 14,
        "id": "messages",
        "title": "صورت حساب",
        "type": "collapsable",
        "parentId": 1,
        "translate": "صورت حساب",
        "children": [
            {
                "icon": "monetization_on",
                "menuId": 18,
                "id": "messages",
                "title": "فاکتور",
                "type": "basic",
                "parentId": 14,
                "translate": "فاکتور",
                "link": "/main/factor",
                "children": [],
            },
            /* {
                 "icon": "monetization_on",
                 "menuId": 19,
                 "id": "messages",
                 "title": "هزینه ها",
                 "type": "basic",
                 "parentId": 14,
                 "translate": "هزینه ها",
                 "link": "/main/costs",
                 "children": [],
             },*/
        ],
    },
    {
        "icon": "web_asset",
        "menuId": 42,
        "id": "messages",
        "title": "api-store",
        "type": "collapsable",
        "parentId": 1,
        "translate": "api-store",
        "children": [
            {
                "icon": "assignment",
                "menuId": 43,
                "id": "messages",
                "title": "کارتابل صورتحساب",
                "type": "basic",
                "parentId": 1,
                "translate": "کارتابل صورتحساب",
                "link": "/main/bill-store",
                "children": [],
            },
        ]
    },
    {
        "icon": "feedback",
        "menuId": 15,
        "id": "messages",
        "title": "درباره...",
        "type": "basic",
        "parentId": 1,
        "translate": "درباره...",
        "link": "/main/about",
        "children": [],
    },
    {
        "icon": "exit_to_app",
        "menuId": 16,
        "id": "messages",
        "title": "خروج",
        "type": "basic",
        "parentId": 1,
        "translate": "خروج",
        "link": "/sign-out",
        "children": [],
    }
];
export const horizontalNavigation: FuseNavigationItem[] = [
    {
        "icon": "home",
        "menuId": 2,
        "id": "home",
        "title": "صفحه اصلی",
        "type": "basic",
        "parentId": 1,
        "translate": "home",
        "link": "/main/home",
        "children": [],
    },
    {
        "icon": "description",
        "menuId": 3,
        "id": "issueWalletGroup",
        "title": "اطلاعات پایه",
        "type": "collapsable",
        "parentId": 1,
        "translate": "اطلاعات پایه",
        "link": null,
        "children": [
            {
                "icon": "email",
                "menuId": 4,
                "id": "messages",
                "title": "پیام ها",
                "type": "basic",
                "parentId": 3,
                "translate": "پیام ها",
                "link": "/main/messages-management",
                "children": [],
            },
            {
                "icon": "featured_play_list",
                "menuId": 22,
                "id": "messages",
                "title": "قواعد",
                "type": "basic",
                "parentId": 3,
                "translate": "قواعد",
                "link": "/main/rules",
                "children": [],
            }
        ]
    },
    {
        "icon": "settings",
        "menuId": 30,
        "id": "issueWalletGroup",
        "title": "پیکربندی",
        "type": "collapsable",
        "parentId": 1,
        "translate": "پیکربندی",
        "link": null,
        "children": [
            {
                "icon": "device_hub",
                "menuId": 22,
                "id": "messages",
                "title": "هاب داده",
                "type": "basic",
                "parentId": 3,
                "translate": "هاب داده",
                "link": "/main/data-hub",
                "children": [],
            }
        ]
    },

    {
        "icon": "people",
        "menuId": 5,
        "id": "issueWalletGroup",
        "title": "سرویس گیرندگان",
        "type": "collapsable",
        "parentId": 1,
        "translate": "سرویس گیرندگان",
        "link": null,
        "children": [
            {
                "icon": "person",
                "menuId": 8,
                "id": "messages",
                "title": "سازمان",
                "type": "basic",
                "parentId": 5,
                "translate": "سازمان",
                "link": "/main/party",
                "children": [],
            }, {
                "icon": "device_hub",
                "menuId": 9,
                "id": "messages",
                "title": "ماژول",
                "type": "basic",
                "parentId": 5,
                "translate": "ماژول",
                "link": "/main/moduleBase",
                "children": [],
            }
        ],
    },
    {
        "icon": "account_balance",
        "menuId": 19,
        "id": "messages",
        "title": "کلاینت",
        "type": "basic",
        "parentId": 1,
        "translate": "کلاینت",
        "link": "/main/client",
        "children": [],
    },
    {
        "icon": "payments",
        "menuId": 27,
        "id": "payments",
        "title": "کارمزد سرویس",
        "type": "basic",
        "parentId": 1,
        "translate": "کارمزد سرویس",
        "link": "/main/wage-services",
        "children": [],
    },
    {
        "icon": "list_alt",
        "menuId": 10,
        "id": "messages",
        "title": "لیست دسترسی",
        "type": "basic",
        "parentId": 1,
        "translate": "لیست دسترسی",
        "link": "/main/access-list",
        "children": [],
    }, {
        "icon": "device_hub",
        "menuId": 11,
        "id": "messages",
        "title": "مدیاتور",
        "type": "collapsable",
        "parentId": 1,
        "translate": "مدیاتور",
        "children": [
            {
                "icon": "device_hub",
                "menuId": 22,
                "id": "messages",
                "title": "لیست مدیاتور ها",
                "type": "basic",
                "parentId": 11,
                "translate": "لیست مدیاتور ها",
                "link": "/main/mediators",
                "children": [],
            }, {
                "icon": "device_hub",
                "menuId": 20,
                "id": "messages",
                "title": "مدیاتور xml",
                "type": "basic",
                "parentId": 11,
                "translate": "مدیاتور xml",
                "link": "/main/mediatorsXml",
                "children": [],
            },
            {
                "icon": "device_hub",
                "menuId": 21,
                "id": "messages",
                "title": "مدیاتور json",
                "type": "basic",
                "parentId": 1,
                "translate": "مدیاتور json",
                "link": "/main/mediatorsJson",
                "children": [],
            }
        ],
    },
    /* {
         "icon": "supervised_user_circle",
         "menuId": 12,
         "id": "messages",
         "title": "مدیریت کاربران",
         "type": "collapsable",
         "parentId": 1,
         "translate": "مدیریت کاربران",
         "children": [
             {
                 "icon": "account_circle",
                 "menuId": 16,
                 "id": "messages",
                 "title": "کاربران",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "کاربران",
                 "link": "/main/users",
                 "children": [],
             },
             {
                 "icon": "account_circle",
                 "menuId": 17,
                 "id": "messages",
                 "title": "نقش ها",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "نقش ها",
                 "link": "/main/roles",
                 "children": [],
             },
         ],
     },
     {
         "icon": "supervised_user_circle",
         "menuId": 36,
         "id": "messages",
         "title": "مدیریت سیستم",
         "type": "collapsable",
         "parentId": 1,
         "translate": "مدیریت سیستم",
         "children": [
             {
                 "icon": "account_circle",
                 "menuId": 39,
                 "id": "messages",
                 "title": "کاربران",
                 "type": "basic",
                 "parentId": 12,
                 "translate": "آلارمها",
                 "link": "/main/alerts",
                 "children": [],
             },

         ],
     }, */
    {
        "icon": "report",
        "menuId": 13,
        "id": "messages",
        "title": "گزارشات",
        "type": "collapsable",
        "parentId": 1,
        "translate": "گزارشات",
        "children": [
            {
                "icon": "report",
                "menuId": 25,
                "id": "messages",
                "title": "ریز کارکرد سرویس",
                "type": "basic",
                "parentId": 13,
                "translate": "ریز کارکرد سرویس",
                "link": "/main/log-reports",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 26,
                "id": "messages",
                "title": "فراخوانی تجمیعی سرویس‌ها",
                "type": "basic",
                "parentId": 13,
                "translate": "فراخوانی تجمیعی سرویس‌ها",
                "link": "/main/call-services-report",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 40,
                "id": "messages",
                "title": "نموداری",
                "type": "basic",
                "parentId": 13,
                "translate": "نموداری",
                "link": "/main/chart-report",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 44,
                "id": "messages",
                "title": "میزان پاسخ‌دهی",
                "type": "basic",
                "parentId": 13,
                "translate": "میزان پاسخ‌دهی",
                "link": "/main/response-rate",
                "children": [],
            },
            {
                "icon": "report",
                "menuId": 44,
                "id": "messages",
                "title": "میزان پاسخ‌دهی",
                "type": "basic",
                "parentId": 13,
                "translate": "میزان پاسخ‌دهی",
                "link": "/main/response-rate",
                "children": [],
            },
        ],
    }, {
        "icon": "monetization_on",
        "menuId": 14,
        "id": "messages",
        "title": "صورت حساب",
        "type": "collapsable",
        "parentId": 1,
        "translate": "صورت حساب",
        "children": [
            {
                "icon": "monetization_on",
                "menuId": 18,
                "id": "messages",
                "title": "فاکتور",
                "type": "basic",
                "parentId": 14,
                "translate": "فاکتور",
                "link": "/main/factor",
                "children": [],
            },
            /* {
                 "icon": "monetization_on",
                 "menuId": 19,
                 "id": "messages",
                 "title": "هزینه ها",
                 "type": "basic",
                 "parentId": 14,
                 "translate": "هزینه ها",
                 "link": "/main/costs",
                 "children": [],
             },*/
        ],
    },
    {
        "icon": "web_asset",
        "menuId": 42,
        "id": "messages",
        "title": "api-store",
        "type": "collapsable",
        "parentId": 1,
        "translate": "api-store",
        "children": [
            {
                "icon": "assignment",
                "menuId": 43,
                "id": "messages",
                "title": "کارتابل صورتحساب",
                "type": "basic",
                "parentId": 1,
                "translate": "کارتابل صورتحساب",
                "link": "/main/bill-store",
                "children": [],
            },
        ]
    },
    {
        "icon": "feedback",
        "menuId": 15,
        "id": "messages",
        "title": "درباره...",
        "type": "basic",
        "parentId": 1,
        "translate": "درباره...",
        "link": "/main/about",
        "children": [],
    },
    {
        "icon": "exit_to_app",
        "menuId": 16,
        "id": "messages",
        "title": "خروج",
        "type": "basic",
        "parentId": 1,
        "translate": "خروج",
        "link": "/sign-out",
        "children": [],
    }
];
