name: Deploy Angular to GitHub Pages

on:
    push:
        branches: [ "main" ]

permissions:
    contents: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Build Angular App
              run: npm run build:prod

            - name: Postbuild step (copy extra config files)
              run: |
                  mkdir -p dist/rescueenvironment/WEB-INF
                  cp -f deploy-configs/web.xml dist/rescueenvironment/WEB-INF/
                  cp -f deploy-configs/rewrite.config dist/rescueenvironment/WEB-INF/

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist/rescueenvironment
